# Generated by Django 4.2.2 on 2023-12-30 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('private', models.CharField(help_text='Private Key', max_length=150)),
                ('public', models.CharField(help_text='Public Key', max_length=150)),
                ('address', models.CharField(help_text='Address', max_length=150)),
                ('wif', models.CharField(help_text='Wallet Import Format', max_length=150)),
                ('user_id', models.ForeignKey(help_text='User of the address', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
