# Generated by Django 4.2.2 on 2023-12-30 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_received', models.IntegerField(help_text='Total amount received in the Wallet')),
                ('total_sent', models.IntegerField(help_text='Total sent by the wallet')),
                ('balance', models.IntegerField(help_text='Wallet Balance')),
                ('unconfirmed_balance', models.IntegerField(help_text='Nnconfirmed Balance')),
                ('final_balance', models.IntegerField(help_text='Final Balace')),
                ('n_tx', models.IntegerField(help_text='Number of transactions')),
                ('unconfirmed_n_tx', models.IntegerField(help_text='Number of unconfirmed transactions')),
                ('final_n_tx', models.IntegerField(help_text='Final transaction')),
                ('tx_url', models.CharField(help_text='Transaction Url')),
                ('address_id', models.OneToOneField(help_text='Related Address', on_delete=django.db.models.deletion.CASCADE, related_name='address_id', to='app.address')),
            ],
        ),
    ]
