# Generated by Django 4.2.2 on 2023-12-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addressinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinfo',
            name='address_id',
            field=models.OneToOneField(blank=True, help_text='Related Address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_id', to='app.address'),
        ),
    ]
