# Generated by Django 4.2.2 on 2023-12-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_addressinfo_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinfo',
            name='tx_url',
        ),
    ]
