# Generated by Django 4.2.2 on 2023-12-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='block_height',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ref_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='spent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_input_n',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_output_n',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fees',
            field=models.IntegerField(default=0, help_text='Fees'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='preference',
            field=models.CharField(default='', help_text='Preference'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received',
            field=models.DateTimeField(blank=True, help_text='Received time', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='relayed_by',
            field=models.CharField(default='', help_text='Relayed by'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.IntegerField(default=0, help_text='Total amount'),
        ),
    ]
