# Generated by Django 4.2.2 on 2023-12-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_transaction_block_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tx_hash',
            new_name='hash',
        ),
        migrations.AddField(
            model_name='transaction',
            name='block_height',
            field=models.IntegerField(default=0, help_text='Block Height'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='block_index',
            field=models.IntegerField(default=0, help_text='Block Index'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='size',
            field=models.IntegerField(default=0, help_text='Size'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ver',
            field=models.IntegerField(default=0, help_text='ver'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vin_sz',
            field=models.IntegerField(default=0, help_text='vin_sz'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vout_sz',
            field=models.IntegerField(default=0, help_text='vout_sz'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vsize',
            field=models.IntegerField(default=0, help_text='vSize'),
        ),
    ]
