# Generated by Django 4.2.2 on 2023-12-31 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_tx_hash_transaction_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_address_id',
            field=models.ForeignKey(help_text='Related Address', on_delete=django.db.models.deletion.CASCADE, related_name='from_address_id', to='app.address'),
        ),
    ]
