version: "3.3"
services:
    app:
        build:
            context: .
            dockerfile: django.Dockerfile
        image: image_${appname}
        container_name: container_${appname}
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        environment:
            - TZ=${TZ_V}
        volumes:
            - ./src:/src
            - ./data/web:/vol/web
        depends_on:
            - db
    db:
        hostname: ${POSTGRES_HOST}
        image: postgres:13-alpine
        volumes:
            - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}